# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5ffa9e1182080452451970a1c965e9db"
name = "my-checkout-extension"
handle = "my-checkout-extension-55"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "hc-sandbox.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_write_customers,read_customers,read_locations,read_shipping,unauthenticated_read_product_pickup_locations,write_shipping"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
